package ak3s

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io/fs"
	"net/url"
	"path/filepath"
	"syscall"
)

const (
	// KillallPath is the cleanup helper generated by the official installer.
	KillallPath = "/usr/local/bin/k3s-killall.sh"
	// RemovalScriptPath retains the unmodified generated script across interrupted removal.
	RemovalScriptPath = "/var/lib/ak3s/uninstall.sh"
	// RemovalKillallPath retains the generated helper needed by that script.
	RemovalKillallPath = "/var/lib/ak3s/killall.sh"
)

func uninstallPath(role string) string {
	return "/usr/local/bin/" + serviceName(role) + "-uninstall.sh"
}

func fingerprint(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

// installK3s gives the unmodified upstream installer a private release directory.
// curl reads file URLs, so upstream verifies and installs the exact prepared bytes
// without a second network download or a moving release channel.
func installK3s(ctx context.Context, p Plan, b *Bundle, runner Runner, write func(string, []byte, fs.FileMode) error) error {
	if err := Verify(b.Installer, p.Pins.Installer.SHA256); err != nil {
		return fmt.Errorf("verify K3s installer: %w", err)
	}
	if err := Verify(b.K3s, p.Pins.K3sSHA256[p.Snapshot.Arch]); err != nil {
		return fmt.Errorf("verify K3s binary: %w", err)
	}
	root, err := filepath.Abs(filepath.Join(b.Dir, "k3s-artifacts"))
	if err != nil {
		return err
	}
	asset := "k3s"
	if p.Snapshot.Arch == "arm64" {
		asset += "-arm64"
	}
	release := filepath.Join(root, p.Pins.K3s)
	if err = write(filepath.Join(release, asset), b.K3s, 0600); err != nil {
		return err
	}
	manifest := p.Pins.K3sSHA256[p.Snapshot.Arch] + "  " + asset + "\n"
	if err = write(filepath.Join(release, "sha256sum-"+p.Snapshot.Arch+".txt"), []byte(manifest), 0600); err != nil {
		return err
	}
	artifactURL := (&url.URL{Scheme: "file", Path: root}).String()
	_, err = runner.Run(ctx, Command{
		Name: "/bin/sh", Args: []string{"-s", "-", p.Config.Node.Role, "--config", ConfigPath}, Input: b.Installer,
		IsolatedEnv: true,
		Env: []string{
			"HOME=" + b.Dir,
			"INSTALL_K3S_VERSION=" + p.Pins.K3s,
			"INSTALL_K3S_ARTIFACT_URL=" + artifactURL,
			"INSTALL_K3S_BIN_DIR=/usr/local/bin",
			"INSTALL_K3S_SYSTEMD_DIR=/etc/systemd/system",
			// K3s does not include config.yaml in its restart comparison. Also
			// force a restart to recover an inactive or interrupted installation.
			fmt.Sprintf("INSTALL_K3S_FORCE_RESTART=%t", p.Restart || !p.Snapshot.ServiceActive),
		},
	})
	if err != nil {
		return fmt.Errorf("official K3s installer: %w; keep the configuration and rerun the same command", err)
	}
	return nil
}

// generatedScripts records trusted installer output without printing script contents.
func generatedScripts(r Reader, role string) (map[string]string, error) {
	result := map[string]string{}
	for _, path := range []string{uninstallPath(role), KillallPath} {
		data, err := readPrivateScript(r, path)
		if err != nil {
			return nil, err
		}
		result[path] = fingerprint(data)
	}
	return result, nil
}

func readPrivateScript(r Reader, path string) ([]byte, error) {
	info, err := r.Lstat(path)
	if err != nil {
		return nil, fmt.Errorf("inspect generated script %s: %w", path, err)
	}
	if !info.Mode().IsRegular() || info.Mode().Perm()&0022 != 0 {
		return nil, fmt.Errorf("generated script must be a regular file writable only by root: %s", path)
	}
	if stat, ok := info.Sys().(*syscall.Stat_t); ok && stat.Uid != 0 {
		return nil, fmt.Errorf("generated script must be owned by root: %s", path)
	}
	data, err := r.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if len(data) == 0 {
		return nil, errors.New("generated K3s script is empty")
	}
	return data, nil
}
